### PR TITLE
Move Path from comment to After Element HTML

### LINKED ISSUE #33: Comments not translated
The method `\AvS\ScopeHint\Plugin\ConfigFieldPlugin::afterGetComment()` adds the configuration code to each comment.

Problem then is that the strings aren't translated anymore.

For example when I have a the comment `Enables or disables Payment Reminder module.` for a label in my custom module, and a translation text in my i18n/de_DE.csv then the afterGetComment() method changes the comment to `Enables or disables Payment Reminder module. <br />Path: <code>path/to/comment</code>` and that can't be translated anymore.

### PR DESCRIPTION
**Pull request by NathanDayFE**
resolves #33

### CODE REVIEW

**Comment by NathanDayFE** [comment]
@avstudnitz Any chance of having this PR reviewed?

**Comment by NathanDayFE** [comment]
@avstudnitz Apologies for double tagging but is there any chance of having this PR reviewed and merged?

**Comment by lefte** [comment]
_**Hello, future search engine result people such as myself!**_ In case you get to this result via some form of a Magento error in management about Phrase and getText() as a string, know that this patch can fix your issue until @avstudnitz merges in this commit or fixes it another way. Here's how I solved it:

1. Modify your `composer.json` file by adding the patch repository to the repositories section:
```
    "repositories": {
         "avsscopehintpatch": {
            "type": "git",
            "url": "https://github.com/NathanDayFE/AvS_ScopeHint2"
        },
        ...any other repos here
    }
```
2. Require the package with this:
```
    "require": {
        "avstudnitz/scopehint2": "dev-comment-phrase#cb2cfa4",
        ....any other packages here
    }
```
> ℹ️ **Note:** The `dev-` in the package version is composer magic to let it know to use the branch instead of a release number, and the `#cb2cfa4` is the hash of the specific commit in the new repo. The commit is not required, but I like to use it for specificity, and so you don't have to use `composer clear-cache` when new commits are added.
3. Update composer using: `composer upgrade avstudnitz/scopehint2`
4. Run `bin/magento setup:upgrade` to finalize
5. Set yourself a calendar reminder to check back on this patch in a month to see if you can use the standard install instead because it's been officially patched in
6. Enjoy Magento
7. _Repeat 5 & 6 as needed_

Thanks again @NathanDayFE for the work on this patch!

**Comment by norgeindian** [comment]
@avstudnitz , could this be merged? This would help us a lot, as the module would then be again compatible with the enterprise edition.

**Comment by avstudnitz** [comment]
Sorry @NathanDayFE @norgeindian - it seems I didn't get any emails or other reminders about that, and I didn't check this repo regularily.
I'll check this.

**Comment by avstudnitz** [comment]
Tested and merged. Thanks @NathanDayFE for your contribution!

**Comment by norgeindian** [comment]
Awesome, thanks a lot for merging.

**Pull request merged**
