### PR TITLE
Optionally show path for configuration options

### PR DESCRIPTION
**Pull request by fredden**
I've set the default to be off, but can trivially set this on by default by creating a `etc/config.xml` file with this set on if you would prefer.

### CODE REVIEW

**Comment by avstudnitz** [comment]
@fredden Thank you, looks good! Please set the default value to "on" as it's one of the most used features of this module, and I don't want to confuse people if they update and suddenly the path is not shown any more.

**Comment by fredden** [comment]
I've made this change and tested again.

**Comment by peterjaap** [comment]
I guess this one can be merged @avstudnitz ?

**Comment by avstudnitz** [comment]
It can @peterjaap. Thanks @fredden! Also thanks for your patience :-)

**Pull request merged**
