### PR TITLE
Return result if registry does not return a product.

### PR DESCRIPTION
**Pull request by jvanschie**

### CODE REVIEW

**Comment by jvanschie** [comment]
This pull request is related to this: [issue](https://github.com/avstudnitz/AvS_ScopeHint2/issues/17)

**Comment by jvanschie** [comment]
> This pull request is related to this issue: [issue](https://github.com/avstudnitz/AvS_ScopeHint2/issues/17)

**Comment by robbertstevens** [comment]
@avstudnitz can you merge this?

**Comment by robbertstevens** [comment]
@avstudnitz can you also create a new version?

**Comment by avstudnitz** [comment]
Sure.

**Pull request merged**
